
unless Vagrant.has_plugin?("vagrant-reload")
  raise 'vagrant-reload is not installed!'
end

Vagrant.configure(2) do |config|

  config.vm.box = "hashicorp/precise32"
  
  config.vm.hostname = "lambdaficator"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
	# Customize the amount of memory on the VM:
    vb.memory = "1024"
	vb.name = "lambdaficator"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
	sudo apt-get autoclean
	sudo apt-get clean
	sudo dpkg --configure -a
	sudo apt-get update -y
	sudo apt-get install -f
	sudo apt-get install ubuntu-desktop -y
	sudo apt-get install lightdm -y
	echo "autologin-user=vagrant" | sudo tee --append /etc/lightdm/lightdm.conf	
  SHELL

  # Reboot the VM to make sure the GUI comes into effect
  config.vm.provision :reload
	
  config.vm.provision "shell", inline: <<-SHELL
	# Install Java
	sudo echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
	sudo add-apt-repository ppa:webupd8team/java -y
	sudo apt-get update -y
	sudo apt-get install oracle-java8-installer -y
	sudo wget --no-check-certificate https://github.com/aglover/ubuntu-equip/raw/master/equip_java8.sh && bash equip_java8.sh
	
	# Install NetBeans
	sudo wget -O /opt/netbeans-8.1-linux.sh http://download.netbeans.org/netbeans/8.1/final/bundles/netbeans-8.1-linux.sh
	cd /opt
	sudo chmod 755 netbeans-8.1-linux.sh
	sudo ./netbeans-8.1-linux.sh --silent --jdkhome /usr/lib/jvm/java-8-oracle/
	
	# Download the NetBeans shortcut
	sudo wget -O /home/vagrant/Desktop/netbeans-8.1.desktop https://raw.githubusercontent.com/SoftwareEngineeringToolDemos/ICSE-2013-LAMBDAFICATOR/master/build-vm/netbeans-8.1.desktop
	chmod 755 /home/vagrant/Desktop/netbeans-8.1.desktop
	
	# Add NetBeans to the startup programs
	sudo mkdir /home/vagrant/.config/autostart
	sudo cp /home/vagrant/Desktop/netbeans-8.1.desktop /home/vagrant/.config/autostart/
	
	# Download Installation.txt, Readme and License.

	sudo wget -O /home/vagrant/Desktop/Installation.txt https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-LAMBDAFICATOR/blob/master/build-vm/Installation.txt
	sudo wget -O /home/vagrant/Desktop/README.txt https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-LAMBDAFICATOR/blob/master/build-vm/Readme
	sudo wget -O /home/vagrant/Desktop/license https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-LAMBDAFICATOR/blob/master/build-vm/LICENSE.txt
		
	{
		echo '[Desktop Entry]'
		echo 'Name=Link to Lambdaficator video Demo'
		echo 'Type=Link'
		echo 'URL=http://youtu.be/MAo5UzADux0'
		echo 'Icon=text-html'
	} > /home/vagrant/Desktop/youtube.desktop

	# Download the required project and modify permissions accordingly
	sudo wget -O /home/vagrant/Downloads/lambda_test.zip	https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-LAMBDAFICATOR/raw/master/build-vm/lambda_test.zip
	cd /home/vagrant/Desktop
	unzip -o /home/vagrant/Downloads/lambda_test.zip
	sudo chmod -R 777 Lambda_Test
  
	# Remove icons from the launcher. Only leave the icons for home directory, settings and firefox.
	sudo mkdir /home/vagrant/icons_backup
	sudo mv /usr/share/applications/ubuntu-software-center.desktop /home/vagrant/icons_backup
	sudo mv /usr/share/applications/ubuntuone-installer.desktop /home/vagrant/icons_backup
	sudo mv /usr/share/applications/libreoffice-*.desktop /home/vagrant/icons_backup	
  SHELL
	
  # Reboot the machine so that eclipse picks up projects from the new workspace upon startup
  config.vm.provision :reload
end
